FROM anapsix/alpine-java:8_server-jre_unlimited

RUN mkdir -p /app-server-test

WORKDIR /app-server-test

EXPOSE 7078

ADD ./app-server/target/app-server-0.0.1-SNAPSHOT.jar ./

CMD java -Djava.security.egd=file:/dev/./urandom -Dserverside.serverName=server-test -Dserver.port=7078 -jar app-server-0.0.1-SNAPSHOT.jar