FROM anapsix/alpine-java:8_server-jre_unlimited

RUN mkdir -p /app-server-formal

WORKDIR /app-server-formal

EXPOSE 7077

ADD ./app-server/target/app-server-0.0.1-SNAPSHOT.jar ./

CMD java -Djava.security.egd=file:/dev/./urandom -Dserverside.serverName=server-formal -Dserver.port=7077 -jar app-server-0.0.1-SNAPSHOT.jar